version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '8090:8090'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      - ./backend/ .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend-build:
  nginx_data:
  letsencrypt: